In [64]:
import pandas as pd
df=pd.read_csv("census.csv")
df.head(10)

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K
5,37,Private,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,0.0,40.0,United-States,<=50K
6,49,Private,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K
7,52,Self-emp-not-inc,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K
8,31,Private,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,0.0,50.0,United-States,>50K
9,42,Private,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178.0,0.0,40.0,United-States,>50K

In [65]:
df.drop(['education_level','education-num','capital-gain','capital-loss','hours-per-week','native-country','marital-status','age'],axis=1,inplace=True)
df

,workclass,occupation,relationship,race,sex,income
0,State-gov,Adm-clerical,Not-in-family,White,Male,<=50K
1,Self-emp-not-inc,Exec-managerial,Husband,White,Male,<=50K
2,Private,Handlers-cleaners,Not-in-family,White,Male,<=50K
3,Private,Handlers-cleaners,Husband,Black,Male,<=50K
4,Private,Prof-specialty,Wife,Black,Female,<=50K
5,Private,Exec-managerial,Wife,White,Female,<=50K
6,Private,Other-service,Not-in-family,Black,Female,<=50K
7,Self-emp-not-inc,Exec-managerial,Husband,White,Male,>50K
8,Private,Prof-specialty,Not-in-family,White,Female,>50K
9,Private,Exec-managerial,Husband,White,Male,>50K
10,Private,Exec-managerial,Husband,Black,Male,>50K
11,State-gov,Prof-specialty,Husband,Asian-Pac-Islander,Male,>50K
12,Private,Adm-clerical,Own-child,White,Female,<=50K
13,Private,Sales,Not-in-family,Black,Male,<=50K
14,Private,Transport-moving,Husband,Amer-Indian-Eskimo,Male,<=50K
15,Self-emp-not-inc,Farming-fishing,Own-child,White,Male,<=50K
16,Private,Machine-op-inspct,Unmarried,White,Male,<=50K
17,Private,Sales,Husband,White,Male,<=50K
18,Self-emp-not-inc,Exec-managerial,Unmarried,White,Female,>50K
19,Private,Prof-specialty,Husband,White,Male,>50K
20,Private,Other-service,Unmarried,Black,Female,<=50K
21,Federal-gov,Farming-fishing,Husband,Black,Male,<=50K
22,Private,Transport-moving,Husband,White,Male,<=50K
23,Private,Tech-support,Unmarried,White,Female,<=50K
24,Local-gov,Tech-support,Husband,White,Male,>50K
25,Private,Craft-repair,Own-child,White,Male,<=50K
26,Private,Exec-managerial,Not-in-family,White,Male,<=50K
27,Private,Craft-repair,Husband,White,Male,<=50K
28,Local-gov,Protective-serv,Not-in-family,White,Male,<=50K
29,Private,Sales,Own-child,Black,Male,<=50K
...,...,...,...,...,...,...
45192,Private,Machine-op-inspct,Not-in-family,Black,Male,<=50K
45193,Private,Machine-op-inspct,Not-in-family,White,Male,<=50K
45194,Self-emp-inc,Exec-managerial,Husband,White,Male,>50K
45195,Private,Prof-specialty,Husband,White,Male,>50K
45196,Private,Tech-support,Not-in-family,White,Female,<=50K
45197,Private,Prof-specialty,Husband,White,Male,>50K
45198,Local-gov,Exec-managerial,Husband,White,Male,>50K
45199,Private,Machine-op-inspct,Own-child,White,Male,<=50K
45200,Self-emp-inc,Exec-managerial,Not-in-family,White,Female,<=50K
45201,Private,Protective-serv,Husband,White,Male,<=50K
45202,Private,Sales,Other-relative,White,Female,<=50K
45203,Private,Sales,Not-in-family,White,Female,<=50K
45204,Private,Prof-specialty,Husband,White,Male,>50K
45205,Private,Craft-repair,Husband,White,Male,<=50K
45206,Private,Craft-repair,Own-child,White,Male,<=50K
45207,Self-emp-not-inc,Farming-fishing,Not-in-family,White,Male,<=50K
45208,Private,Priv-house-serv,Not-in-family,White,Female,<=50K
45209,Private,Adm-clerical,Unmarried,Black,Female,<=50K
45210,Private,Prof-specialty,Not-in-family,White,Male,<=50K
45211,Private,Handlers-cleaners,Husband,White,Male,<=50K
45212,Private,Adm-clerical,Husband,White,Male,<=50K
45213,Private,Sales,Husband,White,Male,<=50K
45214,Private,Craft-repair,Husband,White,Male,<=50K
45215,Private,Other-service,Own-child,White,Female,<=50K
45216,Local-gov,Other-service,Not-in-family,White,Male,<=50K
45217,Private,Prof-specialty,Own-child,White,Male,<=50K
45218,Private,Prof-specialty,Not-in-family,White,Female,<=50K
45219,Private,Prof-specialty,Husband,White,Male,<=50K
45220,Private,Adm-clerical,Own-child,Asian-Pac-Islander,Male,<=50K
45221,Self-emp-inc,Exec-managerial,Husband,White,Male,>50K

In [66]:
inputs=df.drop('income',axis='columns')
target=df['income']

In [67]:
inputs

,workclass,occupation,relationship,race,sex
0,State-gov,Adm-clerical,Not-in-family,White,Male
1,Self-emp-not-inc,Exec-managerial,Husband,White,Male
2,Private,Handlers-cleaners,Not-in-family,White,Male
3,Private,Handlers-cleaners,Husband,Black,Male
4,Private,Prof-specialty,Wife,Black,Female
5,Private,Exec-managerial,Wife,White,Female
6,Private,Other-service,Not-in-family,Black,Female
7,Self-emp-not-inc,Exec-managerial,Husband,White,Male
8,Private,Prof-specialty,Not-in-family,White,Female
9,Private,Exec-managerial,Husband,White,Male
10,Private,Exec-managerial,Husband,Black,Male
11,State-gov,Prof-specialty,Husband,Asian-Pac-Islander,Male
12,Private,Adm-clerical,Own-child,White,Female
13,Private,Sales,Not-in-family,Black,Male
14,Private,Transport-moving,Husband,Amer-Indian-Eskimo,Male
15,Self-emp-not-inc,Farming-fishing,Own-child,White,Male
16,Private,Machine-op-inspct,Unmarried,White,Male
17,Private,Sales,Husband,White,Male
18,Self-emp-not-inc,Exec-managerial,Unmarried,White,Female
19,Private,Prof-specialty,Husband,White,Male
20,Private,Other-service,Unmarried,Black,Female
21,Federal-gov,Farming-fishing,Husband,Black,Male
22,Private,Transport-moving,Husband,White,Male
23,Private,Tech-support,Unmarried,White,Female
24,Local-gov,Tech-support,Husband,White,Male
25,Private,Craft-repair,Own-child,White,Male
26,Private,Exec-managerial,Not-in-family,White,Male
27,Private,Craft-repair,Husband,White,Male
28,Local-gov,Protective-serv,Not-in-family,White,Male
29,Private,Sales,Own-child,Black,Male
...,...,...,...,...,...
45192,Private,Machine-op-inspct,Not-in-family,Black,Male
45193,Private,Machine-op-inspct,Not-in-family,White,Male
45194,Self-emp-inc,Exec-managerial,Husband,White,Male
45195,Private,Prof-specialty,Husband,White,Male
45196,Private,Tech-support,Not-in-family,White,Female
45197,Private,Prof-specialty,Husband,White,Male
45198,Local-gov,Exec-managerial,Husband,White,Male
45199,Private,Machine-op-inspct,Own-child,White,Male
45200,Self-emp-inc,Exec-managerial,Not-in-family,White,Female
45201,Private,Protective-serv,Husband,White,Male
45202,Private,Sales,Other-relative,White,Female
45203,Private,Sales,Not-in-family,White,Female
45204,Private,Prof-specialty,Husband,White,Male
45205,Private,Craft-repair,Husband,White,Male
45206,Private,Craft-repair,Own-child,White,Male
45207,Self-emp-not-inc,Farming-fishing,Not-in-family,White,Male
45208,Private,Priv-house-serv,Not-in-family,White,Female
45209,Private,Adm-clerical,Unmarried,Black,Female
45210,Private,Prof-specialty,Not-in-family,White,Male
45211,Private,Handlers-cleaners,Husband,White,Male
45212,Private,Adm-clerical,Husband,White,Male
45213,Private,Sales,Husband,White,Male
45214,Private,Craft-repair,Husband,White,Male
45215,Private,Other-service,Own-child,White,Female
45216,Local-gov,Other-service,Not-in-family,White,Male
45217,Private,Prof-specialty,Own-child,White,Male
45218,Private,Prof-specialty,Not-in-family,White,Female
45219,Private,Prof-specialty,Husband,White,Male
45220,Private,Adm-clerical,Own-child,Asian-Pac-Islander,Male
45221,Self-emp-inc,Exec-managerial,Husband,White,Male

In [68]:
target

0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
5        <=50K
6        <=50K
7         >50K
8         >50K
9         >50K
10        >50K
11        >50K
12       <=50K
13       <=50K
14       <=50K
15       <=50K
16       <=50K
17       <=50K
18        >50K
19        >50K
20       <=50K
21       <=50K
22       <=50K
23       <=50K
24        >50K
25       <=50K
26       <=50K
27       <=50K
28       <=50K
29       <=50K
         ...
45192    <=50K
45193    <=50K
45194     >50K
45195     >50K
45196    <=50K
45197     >50K
45198     >50K
45199    <=50K
45200    <=50K
45201    <=50K
45202    <=50K
45203    <=50K
45204     >50K
45205    <=50K
45206    <=50K
45207    <=50K
45208    <=50K
45209    <=50K
45210    <=50K
45211    <=50K
45212    <=50K
45213    <=50K
45214    <=50K
45215    <=50K
45216    <=50K
45217    <=50K
45218    <=50K
45219    <=50K
45220    <=50K
45221     >50K
Name: income, Length: 45222, dtype: object

In [69]:
from sklearn.preprocessing import LabelEncoder

In [72]:

le_workclass=LabelEncoder()
le_occupation=LabelEncoder()
le_relationship=LabelEncoder()
le_race=LabelEncoder()
le_sex=LabelEncoder()

In [75]:

inputs['workclass_n']=le_workclass.fit_transform(inputs['workclass'])
inputs['occupation_n']=le_workclass.fit_transform(inputs['occupation'])
inputs['relationship_n']=le_workclass.fit_transform(inputs['relationship'])
inputs['race_n']=le_workclass.fit_transform(inputs['race'])
inputs['sex_n']=le_workclass.fit_transform(inputs['sex'])
inputs.head(10)

,workclass,occupation,relationship,race,sex,workclass_n,occupation_n,relationship_n,race_n,sex_n
0,State-gov,Adm-clerical,Not-in-family,White,Male,5,0,1,4,1
1,Self-emp-not-inc,Exec-managerial,Husband,White,Male,4,3,0,4,1
2,Private,Handlers-cleaners,Not-in-family,White,Male,2,5,1,4,1
3,Private,Handlers-cleaners,Husband,Black,Male,2,5,0,2,1
4,Private,Prof-specialty,Wife,Black,Female,2,9,5,2,0
5,Private,Exec-managerial,Wife,White,Female,2,3,5,4,0
6,Private,Other-service,Not-in-family,Black,Female,2,7,1,2,0
7,Self-emp-not-inc,Exec-managerial,Husband,White,Male,4,3,0,4,1
8,Private,Prof-specialty,Not-in-family,White,Female,2,9,1,4,0
9,Private,Exec-managerial,Husband,White,Male,2,3,0,4,1

In [77]:
inputs_n=inputs.drop(['workclass','occupation','relationship','race','sex'],axis='columns')
inputs_n.head(10)

   workclass_n  occupation_n  relationship_n  race_n  sex_n
0            5             0               1       4      1
1            4             3               0       4      1
2            2             5               1       4      1
3            2             5               0       2      1
4            2             9               5       2      0
5            2             3               5       4      0
6            2             7               1       2      0
7            4             3               0       4      1
8            2             9               1       4      0
9            2             3               0       4      1

In [78]:
from sklearn import tree

In [79]:
model=tree.DecisionTreeClassifier()

In [80]:
model.fit(inputs_n,target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [81]:
model.score(inputs_n,target)

0.8235151032683208

In [82]:
model.predict([[2,7,1,2,0]])

array(['<=50K'], dtype=object)

In [83]:
model.predict([[2,3,0,4,0]])

array(['>50K'], dtype=object)